BO login
teamesa/kilometer_backend pull request #130
Opened 2022-07-30 06:52 UTC by chanhl22

#### BO 로그인

- BO 모든 url 접근 시 로그인 필요

#### 회원가입 로그인/로그아웃
<img width="295" alt="image" src="https://user-images.githubusercontent.com/77683221/181878205-baca5b4b-e0c9-4387-9de6-a843097b6bb5.png">

- 접근 권한은 현재 ADMIN으로 설정
- /account/ADMIN/{username}/{password} (위 이미지처럼 회원가입 가능)

#### account 테이블
<img width="825" alt="image" src="https://user-images.githubusercontent.com/77683221/181878089-cacd290d-4d0b-4adb-bf59-ef6ba913f790.png">

  - username(unique)

2022-07-30 06:58 UTC, azxca1731 requested changes

2022-07-30 06:58 UTC, azxca1731 commented on kilometer-backend-domain/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
이거 제거해주세요

2022-07-30 06:58 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/account/Account.java
> +public class Account {
그냥 account는 너무나 햇갈리니, BackOfficeAccount던 이런 이름으로 바꿔주세요

2022-07-30 06:58 UTC, azxca1731 commented on kilometer-backend-domain/src/main/resources/db/migration/V11__add_account.sql
> +    password    VARCHAR(255)    NOT NULL,
password 암호화 안하고 저장하죠?

2022-07-30 06:58 UTC, azxca1731 commented on kilometer-backend-domain/src/main/resources/db/migration/V11__add_account.sql
> +    password    VARCHAR(255)    NOT NULL,
띠용 아니였네

2022-07-30 06:58 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/account/AccountService.java
> +        accountRequest.encodePassword(passwordEncoder);
인코딩 키는 어디있어요?

2022-08-01 10:46 UTC, chanhl22 commented on kilometer-backend-domain/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-security'
> 이거 제거해주세요

제거했습니다~

2022-08-01 10:52 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/account/AccountService.java
> +        accountRequest.encodePassword(passwordEncoder);
> 인코딩 키는 어디있어요?

SecurityConfiguration 에서 넣어놨어요
```
@Bean
public PasswordEncoder passwordEncoder() {
    return new BCryptPasswordEncoder();
}
```

2022-08-01 10:52 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/account/Account.java
> +public class Account {
수정했습니다~

2022-08-02 13:00 UTC, merged