MyPick 수정
teamesa/kilometer_backend pull request #136
Opened 2022-08-10 06:29 UTC by chanhl22

### 수정사항

1. 최근 등록 순 정렬
2. request DTO 수정

### 참고
- Request
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/77683221/183830284-4beb3f10-d7de-4e2b-9b3f-bef0bca7f4a9.png">

- Response
```
{
  "count": 3,
  "responsePagingStatus": {
    "nextPage": -1,
    "currentPage": 0,
    "pageSize": 0,
    "hasNext": false,
    "totalContentsCount": 3,
    "currentContentsCount": 3
  },
  "contents": [
    {
      "id": 495,
      "presentationImage": {
        "url": "https://kilometer-image.s3.ap-northeast-2.amazonaws.com/static/bo/2022-06-25/075448-%EC%83%81%EC%84%B8%EC%9D%B4%EB%AF%B8%EC%A7%80.jpg",
        "link": "/detail/495",
        "backgroundText": null,
        "dimColor": null,
        "opacity": 0,
        "dimTarget": false
      },
      "typeBadge": {
        "text": "전시회",
        "typeBadge": true
      },
      "additionalBadgeList": [
        {
          "text": "ON",
          "typeBadge": false
        },
        {
          "text": "무료",
          "typeBadge": false
        }
      ],
      "title": {
        "text": "A-Maze-ing",
        "link": "/detail/495"
      },
      "heart": {
        "heartClicked": true,
        "link": "/api/pick/495?status=",
        "id": 495
      },
      "listItemAdditionalInfo": null
    },
    {
      "id": 494,
      
      ...

    },
    {
      "id": 492,
      
      ...

    }
  ]
}
```

2022-08-10 06:34 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        Pageable pageable = pagingStatusService.makePageable(pickRequest.getRequestPagingStatus(), null);
기존의 만들어져있는 makePageable을 재사용하려고 null을 넣었는데
파라미터에 null 값을 넣어도 상관 없나요?

2022-08-10 06:34 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +                .responsePagingStatus(pagingStatusService.convert(pageablePicks, null))
기존의 만들어져있는 convert을 재사용하려고 null을 넣었는데
파라미터에 null 값을 넣어도 상관 없나요?

2022-08-22 14:33 UTC, Kodo92 reviewed
makePageable의 2번째 파라미터에 null을 넣을 경우에 PagingStatusService의 DEFAULT_SORT_OPTION을 사용하도록 되어있는데요, 그것 보다는 myPick의 정렬 기준을 하나 추가하는 것은 어떨까요?

2022-08-22 14:33 UTC, Kodo92 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/PickController.java
>      @PreAuthorize("hasRole('USER')")
지금은 사용하지 않아서 빼도 좋을 것 같아요!

2022-08-22 14:33 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickRepository.java
> +    Page<Pick> findByPickedUserOrderByIdDesc(User user, Pageable pageable);
id 내림차순 정렬하는 이유는 무엇이에요?

2022-08-22 23:30 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickRepository.java
> +    Page<Pick> findByPickedUserOrderByIdDesc(User user, Pageable pageable);
> id 내림차순 정렬하는 이유는 무엇이에요?

지난 스프린트에서 최근 등록 순 정렬 요청이 있었습니다

2022-08-23 04:50 UTC, chanhl22 commented
> makePageable의 2번째 파라미터에 null을 넣을 경우에 PagingStatusService의 DEFAULT_SORT_OPTION을 사용하도록 되어있는데요, 그것 보다는 myPick의 정렬 기준을 하나 추가하는 것은 어떨까요?

search api 같은 경우는 정렬 기준이 필요하지만 여기서는 최근 등록 순으로 정렬하기로 했어서 애초에 findByPickedUserOrderByIdDesc 처럼 정렬을 했거든요,
사실상 Pageable 객체의 Sort를 사용하지 않아도 되는데 기존에 만들어진 makePageable 메소드를 사용하려고 null을 넣었어요.
근데 이렇게 하는거보다 정렬 기준을 하나 추가해서 Pageable 객체의 Sort를 사용하는게 낫나요??

2022-08-23 13:07 UTC, azxca1731 requested changes

2022-08-23 13:07 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        Preconditions.notNull(pickRequest.getRequestPagingStatus(), String.format("this service can not be run will null object, please check this, %s", pickRequest));
두 로그가 똑같은 것 같아요. 로그는 백엔드에서 얼마 확인가능한 Symptom입니다. 많이 찍으면 찍을 수록 좋고, 명확하면 명확할 수 록 좋아요.

2022-08-23 13:07 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        Pageable pageable = pagingStatusService.makePageable(pickRequest.getRequestPagingStatus(), null);
음 사실상 Sort가 있어서 null이어도 괜찮을 것 같긴한데, 이참에 어떻게 JPA에서는 Sort하는지 공부해보실래요?

2022-08-23 13:07 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +                .responsePagingStatus(pagingStatusService.convert(pageablePicks, null))
네네 쿼리는 상관 없습니다.
근데 만약에 이런 경우가 있다면, 사용하는 쪽에서 null을 넣지 말고, 
ResponsePagingStatus convert(Page page, String query)를 
ResponsePagingStatus convert(Page page) 로 만들어서 사용해주세요

2022-08-23 13:07 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/dto/PickRequest.java
> +@AllArgsConstructor
이건 왜 필요한가요?

2022-08-23 15:00 UTC, Kodo92 commented
> > makePageable의 2번째 파라미터에 null을 넣을 경우에 PagingStatusService의 DEFAULT_SORT_OPTION을 사용하도록 되어있는데요, 그것 보다는 myPick의 정렬 기준을 하나 추가하는 것은 어떨까요?
> 
> search api 같은 경우는 정렬 기준이 필요하지만 여기서는 최근 등록 순으로 정렬하기로 했어서 애초에 findByPickedUserOrderByIdDesc 처럼 정렬을 했거든요, 사실상 Pageable 객체의 Sort를 사용하지 않아도 되는데 기존에 만들어진 makePageable 메소드를 사용하려고 null을 넣었어요. 근데 이렇게 하는거보다 정렬 기준을 하나 추가해서 Pageable 객체의 Sort를 사용하는게 낫나요??

우선 기획측에 최근 등록순이 어떤것인지 확인해볼 필요가 있을 것 같아요. 
제가 알기로는 updateAt을 기준으로 정렬하고 있는 것들이 많거든요!
극단적인 예시로 10년전에 pick한 것을 5년전에 pick 취소를 했고 오늘 다시 pick을 한다면 row를 update하기 때문에 가장 최근에 pick한 것일지라도 제일 뒤로 밀릴 수 있을 것 같아요 :)

또한 makePageable()에서 두번째 파라미터가 NULL일 때 들어가는 default option은 SearchSortType을 사용하고 있고, 이것은 검색할 때 사용기에 부적절한 의존관계라고 생각합니다아...

2022-08-24 02:05 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +                .responsePagingStatus(pagingStatusService.convert(pageablePicks, null))
> 네네 쿼리는 상관 없습니다. 근데 만약에 이런 경우가 있다면, 사용하는 쪽에서 null을 넣지 말고, ResponsePagingStatus convert(Page page, String query)를 ResponsePagingStatus convert(Page page) 로 만들어서 사용해주세요

수정 완료!

2022-08-24 02:05 UTC, chanhl22 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/PickController.java
>      @PreAuthorize("hasRole('USER')")
> 지금은 사용하지 않아서 빼도 좋을 것 같아요!

수정 완료!

2022-08-24 02:06 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/dto/PickRequest.java
> +@AllArgsConstructor
> 이건 왜 필요한가요?

수정 완료!

2022-08-24 14:31 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/PickController.java
> +        return pickService.getMyPick(pickRequest, getLoginUserId());
getMyPick 복수형으로 해주세용

2022-08-24 14:34 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/paging/PagingStatusService.java
> +        Sort sort = Optional.ofNullable(sortType)
이 Sort가 들어간 이유가 있을까요?

2022-08-24 14:34 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/dto/PickSortType.java
> +public enum PickSortType {
이 클래스의 이유는 뭐죠?

2022-08-24 23:09 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/paging/PagingStatusService.java
> +        Sort sort = Optional.ofNullable(sortType)
myPick이 최근 pick 한 순서로 들어가기 때문에 넣어줬습니다.

2022-08-24 23:15 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/dto/PickSortType.java
> +public enum PickSortType {
사실 SearchSortType 에다가 정렬하는 값을 추가하는게 코드 자체는 더 깔끔하긴 한대, search랑 pick을 분리하는게 더 낫다고 생각해서 추가했습니다

2022-08-31 11:44 UTC, azxca1731 approved these changes

2022-08-31 13:08 UTC, merged