fix : 무한으로 pick count 증가 수정
teamesa/kilometer_backend pull request #137
Opened 2022-08-22 14:08 UTC by Kodo92

- PickService 수정
- 자동 줄 정렬

2022-08-23 05:03 UTC, chanhl22 approved these changes

2022-08-23 12:56 UTC, azxca1731 commented on kilometer-backend-api/src/main/java/com/kilometer/backend/controller/PickController.java
> +        Long userId = getLoginUserId();
드디어 없애주셨군요~ 감사합니당~

2022-08-23 12:59 UTC, azxca1731 requested changes

2022-08-23 12:59 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +                itemService.plusItemPickCount(itemId);
음 2중이라 별로 안 좋아보이네요.
itemService를 변경해서 status도 뭔가 isUserPicked 이런게 더 좋아보이네요.
status가 이름이 모호해보여요.

2022-08-24 14:26 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        String.format("this service can not be run will null object, please check this, %s",
이거 찬희님한테 로그 심을때 이야기 했는데, 두개가 똑같을 거 같아요! 좀 다르게 하는거 어떨까요?

2022-08-24 14:29 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        String.format("this service can not be run will null object, please check this, %s",
이거는 찬희님 영역이어서 제가 수정하면 충돌날것 같습니다.
찬희님 PR에서 수정한 다음 MERGE 하는게 맞을 것 같아요!

2022-08-24 14:29 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +    private boolean isAlreadyPicked(Pick pick, boolean nextPickedStatus) {
저는 원래 생각한건 pick.isHearted() == nextPickedStatus -> 를 조금 더 보기 좋게 하기 위해서 private method로 빼자는 거였어요! 이렇게 하면 조회를 위한 메소드인지, 변경을 위한 메소드인지 햇갈리는 것 같아요

2022-08-24 14:29 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        String.format("this service can not be run will null object, please check this, %s",
네네넵

2022-08-24 14:43 UTC, azxca1731 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        if(!isAlreadyPicked(pick, nextPickedStatus)) {
엇 이런경우엔 위에서 바로 return해주세요. 다시 2중포문이라 ㅠㅠ

2022-08-24 15:14 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/pick/PickService.java
> +        if(!isAlreadyPicked(pick, nextPickedStatus)) {
2중 포문 -> 2중 이프문...
```java
if(isAlreadyPicked(pick, nextPickedStatus)) {
          return PickResponse.builder()
                      .content(pick.isHearted())
                      .build();
          }
            pick.changeIsHearted(nextPickedStatus);
            if (nextPickedStatus) {
                itemService.plusItemPickCount(itemId);
            } else {
                itemService.minusItemPickCount(itemId);
            }

        return PickResponse.builder()
            .content(pickRepository.save(pick).isHearted())
            .build();
```

뭔가 안이쁘지 않나용...

2022-08-27 05:35 UTC, azxca1731 approved these changes

2022-08-27 05:35 UTC, merged