Chanhl22/feature bo image
teamesa/kilometer_backend pull request #96
Opened 2022-06-24 12:30 UTC by chanhl22

BO 이미지 등록, 수정

2022-06-24 13:05 UTC, azxca1731 approved these changes

2022-06-24 13:05 UTC, azxca1731 commented on kilometer-backend-backoffice/src/main/java/com/kilometer/backend/controller/ItemController.java
> +import com.kilometer.domain.item.*;
아스테리스크 하지 말아주세요

2022-06-24 13:05 UTC, azxca1731 commented on kilometer-backend-backoffice/src/main/java/com/kilometer/backend/controller/ItemController.java
> +import org.springframework.web.bind.annotation.*;
아스테리스크 사용금지

2022-06-24 13:05 UTC, azxca1731 commented on kilometer-backend-backoffice/src/main/resources/static/js/image.js
> +var appVue = new Vue({
으익 뷰

2022-06-24 13:05 UTC, azxca1731 commented on kilometer-backend-backoffice/src/main/resources/templates/form/updateItemForm.html
> +        let imageId = Number($(elem).prev().val());
원래 같았으면 IE때문에 let, const등은 피해주시는게 좋아요

2022-06-24 13:32 UTC, Kodo92 requested changes
프론트에서 삭제된 이미지를 판단하고 Update 요청을 보낸다면
1. 서버에서 ItemUpdateDto를 별도로 만들어서 요청을 받아야 할 것 같아요.
  - 여기서 detailImageUrls 삭제
  - deleteDetailImages , newDetailImages 이렇게 필드 두 개로 가면 될 것 같아요.
  - ItemService.saveDetailImage에 newDetailImages를 넣어주도록이요.
2. 사진 URL들을 LIST로 담아 보낼 때 빈 문자열이 들어가는 것 같은데 이유가 있나요?

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-backoffice/src/main/java/com/kilometer/backend/controller/ItemController.java
> +    @GetMapping(BoUrlUtils.ITEM_EDIT)
ITEM 조회하는 부분인데 ITEM_ID로 바꾸신 이유가 있나요?

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-backoffice/src/main/resources/templates/form/items.html
> +                    <form action="" th:action="@{/form/items/edit/{id} (id=${item.id})}" method="get">
굿굿 누락된 부분 수정 잘 해주셨는데, method post로 바꿔주세요!

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemRequest.java
> +    private List<Long> deleteDetailImages = new ArrayList<>();
Request DTO에 삭제될 이미지 id값이 들어간다면 ItemRequest -> ItemUpdateRequest로 DTO 하나 만들어서 분리해주세요!

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemRequest.java
> +    private List<String> detailImageUrls = new ArrayList<>();
ItemUpdateRequest dto로 분리하고 해당 필드는 insertDetailImages로 변경해서 추가되는 이미지 정보를 담아주시면 좋을 것 같아요.
ItemService.update로직에서 save부분에는 insertDetailImages 값들을 추가해주도록 변경해야하구요

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemService.java
>          saveDetailImage(request, item);
이 부분 수정 들어가야합니다~ 아래 코멘트 참고해주세요

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/ItemEntity.java
> +            .detailImageUrlsAndIndex(Optional.ofNullable(this.itemDetailImages)
해당 필드를 사용한다면detailImageUrls 필드를 삭제해도 되지 않을까요?

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemRequest.java
> +            .filter(StringUtils::hasText)
빈 문자열이 왜 존재하나요?

2022-06-24 13:32 UTC, Kodo92 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemResponse.java
> +    private List<ItemDetailImages> detailImageUrlsAndIndex = new ArrayList<>();
해당 필드 사용하실거면 59라인의 detailImageUrls 삭제해야할 것 같아요!

2022-06-24 13:40 UTC, chanhl22 commented on kilometer-backend-backoffice/src/main/java/com/kilometer/backend/controller/ItemController.java
> +    @GetMapping(BoUrlUtils.ITEM_EDIT)
타임리프 뷰에서 수정 폼을 처리할 때 th:action에 값을 안넣고 디폴트값으로 쓰기 위해 바꿨습니다

2022-06-24 13:41 UTC, chanhl22 commented on kilometer-backend-backoffice/src/main/resources/templates/form/items.html
> +                    <form action="" th:action="@{/form/items/edit/{id} (id=${item.id})}" method="get">
이것도 마찬가지로 위에서 edit로 경로를 바꿔서 get으로 보내서 뷰를 받아옵니다.

2022-06-24 13:42 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemRequest.java
> +    private List<Long> deleteDetailImages = new ArrayList<>();
이 부분이 처음에 분리해서 코드를 작성했는데 중복이 많다고 합쳐서 진행한거 아니였나요..??

2022-06-24 13:45 UTC, chanhl22 commented on kilometer-backend-domain/src/main/java/com/kilometer/domain/item/dto/ItemRequest.java
> +            .filter(StringUtils::hasText)
뷰에서 받아올 때 버튼이 추가, 삭제가 반복될 수 있는데
만약 버튼 추가 후에 다시 삭제가 될 경우 빈 데이터가 담기기 때문입니다.

2022-06-24 14:43 UTC, Kodo92 commented on kilometer-backend-backoffice/src/main/resources/templates/form/items.html
> +                    <form action="" th:action="@{/form/items/edit/{id} (id=${item.id})}" method="get">
아 Items 였군요 이해했습니다~

2022-06-25 06:34 UTC, chanhl22 commented
> 프론트에서 삭제된 이미지를 판단하고 Update 요청을 보낸다면
> 
> 1. 서버에서 ItemUpdateDto를 별도로 만들어서 요청을 받아야 할 것 같아요.
> 
> * 여기서 detailImageUrls 삭제
> * deleteDetailImages , newDetailImages 이렇게 필드 두 개로 가면 될 것 같아요.
> * ItemService.saveDetailImage에 newDetailImages를 넣어주도록이요.
> 
> 2. 사진 URL들을 LIST로 담아 보낼 때 빈 문자열이 들어가는 것 같은데 이유가 있나요?

DTO 분리 완료!

2022-06-25 06:35 UTC, Kodo92 approved these changes

2022-06-25 06:37 UTC, merged